### ISSUE TITLE
The Actual BPP for BitsBack

### ISSUE THREAD

**Issue by ryoungj** [mandt-lab/improving-inference-for-neural-image-compression#1]
Hello,

Thanks for sharing the code! I'm going through the code and find that all the evaluation/compression scripts (except `mbt2018.py`) do not actually compress the images into bitstrings and do not contain a decompress function. Have you implemented the actual compression for BitsBack or do you just report the estimated BPP?

Another question is that for BitsBack, it seems that you are using a continuous Gaussian which is not compatible with entropy coding. Do you discretize it somewhere in the code?

**Comment by robamler** [comment]
Thank you for reaching out!

In the paper, we report the information content of the discretized latent representation under the discritized prior model. This is the *exact* bitrate (modulo rounding up to the nearest integer number of bits) that a perfect entropy coder such as Arithmetic Coding will produce in this situation.

In practice, exact Arithmetic Coding is inefficient (in terms of runtime) on typical hardware architectures, but efficient algorithms like Range Coding or Asymmetric Numeral Systems can reach its compression performance asymptotically. @yiboyang tested Range Coding for our model and obtained bitrates that are almost indistinguishable from the true information content. He is currently cleaning up the code for this and I believe will commit it to this repository for the NeurIPS camera ready version of the paper.

Concerning the continuous Gaussian models `p(z)` and `q(z|y)` for bits-back coding: this is a good observation! We didn't discuss this in the paper but with bits-back coding, discretization in the hyperlatent (`z`) space is much less of an issue than discretization in the latent (`y`) space. You can make the discretization grid in z-space arbitrarily dense (thus approximating a continuous Gaussian arbitrarily well) without increasing the bitrate. The denser the grid the more bits are required to encode z using `P(z)`, but also the more bits you'll get back when you decode the side information using `Q(z|x)`. The net bitrate `log_2 Q(z|x) - log_2 P(z)` for encoding z is independent of how dense the discretization is in z-space. This is why we used simple continuous distributions with smooth PDFs in z-space in the bits-back variant of our model.

I'll leave this issue open as a reminder until we've committed the range coder.

**Comment by ryoungj** [comment]
Thanks for the comprehensive response! It's really helpful!

**Comment by yiboyang** [comment]
Sorry for taking a while to follow up on this; there were some complications in getting the range coder in tensorflow-compression to work with SGA for the mean-scale model. Meanwhile, @robamler has added codec support for SGA (with experimental support for the bits-back version, SGA+BB, too) based on range Asymmetric Numeral Systems (rANS) on the [ans-coder branch](https://github.com/mandt-lab/improving-inference-for-neural-image-compression/tree/ans-coder).

Example sequence of commands to run SGA, encode the SGA output (the optimized latents) to a binary file, and then decode it:

```
python sga.py --num_filters 192 --verbose --checkpoint_dir ./checkpoints compress --save_latents mbt2018-num_filters=192-lmbda=0.0025 imgs/kodim08.png --results_dir ./test 

python sga.py --num_filters 192 --verbose --checkpoint_dir ./checkpoints encode_latents mbt2018-num_filters=192-lmbda=0.0025 test/latents-sga-lmbda=0.0025+mbt2018-num_filters=192-lmbda=0.0025-input=kodim08.png.npz 

python sga.py --num_filters 192 --verbose --checkpoint_dir ./checkpoints decode_latents mbt2018-num_filters=192-lmbda=0.0025 test/latents-sga-lmbda=0.0025+mbt2018-num_filters=192-lmbda=0.0025-input=kodim08.png.npz.compressed
```


Again, we verified that the differences in the actual BPP and our reported rate estimates are negligible. As both the encoder and decoder must have access to _identical_ copies of the (discretized) entropy models for correctness, we recommend running the `encoder_latents` and `decode_latents` steps on CPU (setting `CUDA_VISIBLE_DEVICES` to `-1`), otherwise you may encounter an error. The initial (expensive) SGA optimization step can still be run on GPU.
